### PR TITLE
Updated to rails 3

### PR DESCRIPTION
**Pull request by jonleighton**
Hiya,

I've updated param_protected for Rails 3. Perhaps you could pull the changes? Thanks.

[It will probably work on Rails 2.3.8, but the tests won't as the test app is now a Rails 3 app.]

Jon

### CODE REVIEW

**Comment by cjbottaro** [comment]
Hello.  I've been out of town for all of Labor Day Weekend.  I'll try to get to this in a couple of days.  Thanks!

**Comment by dnd** [comment]
Did these changes ever make it in?

**Comment by cjbottaro** [comment]
Shoot not yet, sorry.  I have a major deadline at work, plus I'm out of town most weekends.  I'm going to have to make a branch for the Rails 3 version, get all the test passing, then release to RubyGems as a different major version.  I just need to sit down and do all... a little difficult because I have zero Rails 3 experience.

If you want to get all the tests passing in your fork, then all I'd have to do is make a branch and release it.

**Comment by jonleighton** [comment]
Hi,

Sorry if I wasn't clear but as far as I am concerned you could just pull this and push to Rubygems:
- I updated the tests so that they work with Rails 3 (by updating test/app_root to be a Rails 3 app and modifying test_helper.rb)
- I updated the version number from 1.3.0 to 1.4.0 and regenerated the gemspec
- I made the relevant changes to lib/ to get all the existing tests passing

So it should "just work". Maybe it would help if dnd could pull my fork and try out the tests themselves to give a second opinion.

Cheers

**Comment by jonleighton** [comment]
Hey,

I have just realised that the "official" param_protected branch had moved ahead. So I've merged the new changes and pushed to my branch. The tests still pass.

Cheers

**Comment by cjbottaro** [comment]
Oh, awesome... yeah, sorry for the misunderstanding, would have done it sooner.

Ok, I just merged your stuff into master, bumped the version to 2.0.0 and release to rubygems.org.  I also created a rails23 branch where the version will remain 1.x.x.

Thanks a lot, appreciate it!

**Pull request merged**
